### ISSUE TITLE
Daycount addition 

### ISSUE THREAD

**Issue by treemlt** [xstar97/palworld-query-api#2]
Api is working fine! Would be awsome if you could add the daycount as well

**Comment by xstar97** [comment]
This is a stop gag until gamedig resolves the query issues...i dont think rcon contains that info sadly.

**Comment by xstar97** [comment]
@treemlt guess what? implemented in v0.2.0 :)

**Comment by treemlt** [comment]
Nice ! I cannot find my server in the api. I don't know if i have a missing setting
